name: examen2rober
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  dependencies:
  flutter: 
    sdk: flutter
  firebase_core: ^2.4.0
  cloud_firestore: ^4.3.0
  provider: ^6.0.0
  go_router: ^6.0.0
